apiVersion: apps/v1
kind: Deployment
metadata:
  name: Room-backend
spec:
  selector:
    matchLabels:
      app: Room-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: Room-backend
    spec:
      containers:
      - name: Room-backend
        image: luukschool/room-backend:latest
        ports:
        - containerPort: 5001
