apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: room-backend
  template:
    metadata:
      labels:
        app: room-backend
    spec:
      containers:
      - name: room-backend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
