name: Transfer-Room-backend-Docker-Build
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./ -t luukschool/room-backend:latest
      - name: push image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u luukschool --password-stdin
          docker push luukschool/room-backend:latest